api/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect email or password, try again.', category='error')
        else:
            flash('Incorrect email or password, try again.', category='error')
    return render_template("user/login.html")

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        data = request.form
        email = data.get('email')
        password = data.get('password')
        confirm_password = data.get('confirm_password')

        if len(email) < 4:
            flash("Email length must be greater than 4 characters", category='error')
        elif password != confirm_password:
            flash("Passwords do not match", category='error')
        elif len(password) < 8:
            flash("Password is too short, it must be 8 characters or more", category='error')
        else:
            exists = User.query.filter_by(email=email).first()
            if not exists:
                new_user = User(email=email, password=generate_password_hash(password, method='sha256'))
                db.session.add(new_user)
                db.session.commit()
                flash("Successfully created the account", category='success')
                login_user(new_user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash(f"This email is already registered, try to login with {email}", category='error')

        return render_template("user/register.html", data=email)
    else:
        return render_template("user/register.html")

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/profile')
@login_required
def profile():
    return render_template("user/acc_manage.html", user=current_user)


@auth.route('/profile/update-password', methods=['POST'])
@login_required
def update_password():
    data = request.form
    if current_user.id == int(data.get('user_id')):
        current_password = data.get('current_password')
        new_password = data.get('new_password')
        confirm_password = data.get('password_confirmation')
        user = User.query.filter_by(id=current_user.id).first()

        if check_password_hash(current_user.password, current_password):
            if new_password == confirm_password:
                if len(new_password) < 8:
                    flash("Password is too short, it must be 8 characters or more", category='error')
                else:
                    user.password = generate_password_hash(new_password, method='sha256')
                    db.session.commit()
                    flash("Password updated successfully", category='success')
            else:
                flash("Passwords do not match", category='error')
        else:
            flash("Incorrect password", category='error')
    else:
        flash("Something went wrong", category='error')
    return redirect(url_for('auth.profile'))



@auth.route('/profile/delete', methods=['POST'])
@login_required
def delete_profile():
    user = User.query.filter_by(id=current_user.id).first()
    if user == current_user:
        if check_password_hash(user.password, password):
            reports = Report.query.filter_by(user_id=current_user.id).all()
            for report in reports:
                if report.status == 'pending':
                    celery.control.revoke(report.task_id, terminate=True)
                    db.session.delete(report)
                    db.session.commit()
            db.session.delete(user)
            db.session.commit()
            flash("Account deleted successfully", category='success')
            return redirect(url_for('auth.login'))
        else:
            flash("Incorrect password", category='error')
    else:
        flash("Something went wrong", category='error')
        return redirect(url_for('auth.profile'))

api/templates/user/acc_manage.html
{% extends "user/profile_base.html" %} {% block title %} Account management {% endblock %} {% block profile_content %} <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/">Home</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">Account management</li>
  </ol>
</nav>
<div class="row align-items-center">
  <div class="mt-1">
    <h2> Change password</h2>
  </div>
  <div class="form-group">
    <div class="col-sm-6">
      <form method="post" action={{ url_for('auth.update_password') }} id="change_password_form">
          <input type="hidden" name="user_id" value="{{ user.id }}">
        <div class="mb-3">
          <label for="current_password" class="form-label">Current password</label>
          <input type="password" class="form-control" name="current_password" id="current_password" placeholder="Enter current password">
        </div>
        <div class="mb-3">
          <label for="new_password" class="form-label">New password</label>
          <input type="password" class="form-control" name="new_password" id="new_password" placeholder="Enter new password">
        </div>
        <div class="mb-3">
          <label for="password_confirmation" class="form-label">Confirm new password</label>
          <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="Confirm new password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div>
<hr class="my-4">
<div class="d-flex flex-column align-items-left text-left">
  <div class="mt-1">
    <h2> Delete account</h2>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-6">
    <form method="post" action="/profile/delete" id="delete-account-form">
      <div class="mb-3">
        <label for="password" class="form-label">Current password</label>
        <input type="password" class="form-control" name="password" placeholder="Enter current password">
      </div>
      <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete your account?')">Delete account</button>
    </form>
  </div>
</div>
</form>
{% endblock %}

{% block scripts %}
    <script>
  $(document).ready(function() {
    $("#change_password_form").validate({
      rules: {
        current_password: {
          required: true
        },
        new_password: {
          required: true,
          minlength: 8
        },
        password_confirmation: {
          required: true,
          equalTo: "#new_password"
        }
      },
      messages: {
        old_password: {
          required: "Please enter your old password"
        },
        password: {
          required: "Enter your password"
        },
        password_confirmation: {
          required: "Please confirm your password",
          equalTo: "Passwords do not match"
        }
      }
    });
    $("#delete-account-form").validate({
      rules: {
        password: {
          required: true,
          minlength: 8
        },
      },
      messages: {
        password: {
          required: "Enter your password to delete account",
          minlength: "Password must be at least 8 characters long"
        }
      }
    });
  });
</script> {% endblock %}

api/templates/user/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container" style="margin-top: 100px;">
   <div class="row">
      <div class="col">
      </div>
      <div class="col-12">
         <div class="card">
            <div class="card-body">
    <form method="POST" id="loginForm">
    <h3 class="text-center">Login</h3>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
    <button type="submit" class="btn btn-primary btn-block" style="margin-top: 20px">Login</button>
    </form>
            <p>Don't have an account? <a href="/register">Register</a></p>

            </div>
         </div>
      </div>
      <div class="col">
      </div>
   </div>

{% endblock %}


{% block scripts %}
<script>
        $(document).ready(function() {
        $("#loginForm").validate({
            rules: {
                email: {
                    required: true,
                    email: true,
                    maxlength: 50
                },
                password: {
                    required: true
                }
            },
            messages: {
                email: {
                    required: "Enter your email",
                    email: "Email must be a valid email address",
                    maxlength: "Email cannot be more than 50 characters",
                },
                password: {
                    required: "Enter your password"
                }
            }
        });
    });
</script>
{% endblock %}

api/templates/user/profile_base.html
{% extends 'base.html' %} {% block title %}Profile{% endblock %} {% block content %} <style>
  a:link {
    text-decoration: none;
  }

  a:visited {
    text-decoration: none;
  }

  a:hover {
    text-decoration: none;
  }

  a:active {
    text-decoration: none;
  }
</style>
<div class="row" style="margin-top: 30px">
  <div class="col-lg-4 menu">
    <div class="card">
      <div class="card-body">
        <div class="d-flex flex-column align-items-center text-center">
          <div class="mt-3">
            <div id="profile-container">
              <img src="static/images/default_profile.jpg" alt="profile" class="rounded-circle" width="50">
            </div>
            <h3 class="text-dark font-weight-normal">{{ user.email }}</h3>
          </div>
        </div>
        <hr class="my-4">
        <!--- Profile Menu -->
        <ul id="profile_menu" class="list-group list-group-flush collapse dont-collapse-sm">
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0">
              <a href={{ url_for('auth.profile') }} class="text-dark">
                <i class="fa-solid fa-user"></i> Account management </a>
            </h6>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0">
              <a href={{ url_for('views.reports') }} class="text-dark">
                <i class="fa-solid fa-file"></i> Reports </a>
            </h6>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0">
              <a href={{ url_for('auth.logout') }} class="text-dark">
                <i class="fa-solid fa-arrow-right-from-bracket"></i> Logout </a>
            </h6>
          </li>
        </ul>
        <div>
          <button class="btn btn-outline-secondary d-md-none mt-1 menuToggle" type="button" data-bs-toggle="collapse" data-bs-target="#profile_menu" aria-expanded="false" aria-controls="multiCollapseExample2">Show menu</button>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="card">
      <div class="card-body"> {% block profile_content %}{% endblock %} </div>
    </div>
  </div>
</div>
{% endblock %}

api/templates/user/register.html
{% extends 'base.html' %} {% block title %}Register{% endblock %} {% block content %} <div class="container" style="margin-top: 100px;">
  <div class="row">
    <div class="col"></div>
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <form method="POST" id="regForm">
            <h3 class="text-center">Register</h3>
            <div class="form-group">
              <label>Email</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
              <label>Confirm Password</label>
              <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm Password">
            </div>
            <button type="submit" class="btn btn-primary btn-block" style="margin-top: 20px">Register</button>
          </form>
          <p>Already have an account? <a href="/login">Login here</a>. </p>
        </div>
      </div>
    </div>
    <div class="col"></div>
  </div>
</div>
{% endblock %} {% block scripts %} <script>
    $(document).ready(function() {
      $("#regForm").validate({
        rules: {
          email: {
            required: true,
            email: true,
            maxlength: 50
          },
          password: {
            required: true,
            minlength: 8
          },
          confirm_password: {
            required: true,
            minlength: 8,
            equalTo: "#password"
          }
        },
        messages: {
          email: {
            required: "Email is required",
            email: "Email must be a valid email address",
            maxlength: "Email cannot be more than 50 characters",
          },
          password: {
            required: "Password is required",
            minlength: "Password must be at least 8 characters"
          },
            confirm_password: {
                required: "Confirm password is required",
                minlength: "Confirm password must be at least 8 characters",
                equalTo: "Passwords do not match"
            }
        }
      });
    });
  </script>
{% endblock %}

api/templates/user/report.html
{% extends "user/profile_base.html" %} {% block title %}Report for {{ report.name }}{% endblock %} {% block content %} <div class="container" style="margin-top: 100px;">
  <div class="card">
    <div class="card-body">
      <div class="col-12">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="/">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="/reports">Reports</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{ report.name }}</li>
          </ol>
        </nav>
        <div class="row">
          <div class="col-8">
            <h4>Report for {{ report.name }}</h4>
          </div>
          <div class="col-4">
            <button type="button" class="btn btn-success" onclick="window.location.href='/reports/{{ report.id }}/download'">Download PDF</button>
            <form action="/reports/{{ report.id }}/delete" method="POST" style="display: inline;">
              <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this report?')">Delete</button>
            </form>
          </div>
        </div>
        <br>
        <br>
        <div class="row">
          <div class="col-12">
            <h6>Nmap scan results:</h6>
          </div>
          <div class="col-12">
           <div class="card">
            <div class="card-body">
                <pre>{{ report.nmap_report }}</pre>
            </div>
          </div>
        </div>
        </div>
        <br>
        <div class="row">
          <div class="col-12">
            <h6>Nikto scan results:</h6>
          </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <pre>{{ report.nikto_report }}</pre>
                    </div>
                </div>
            </div>
        </div>
        <br>
      </div>
        <div class="row">
          <div class="col-12">
            <h6>Gobuster scan results:</h6>
          </div>
            <div class="col-12">
                <div class="card">
                <div class="card-body">
                    <pre>{{ report.dirb_report }}</pre>
                </div>
                </div>
      </div>
    </div>
<br>
        <div class="row">
          <div class="col-12">
            <h6>Misc scan results:</h6>
          </div>
            <div class="col-12">
                <div class="card">
                <div class="card-body">
                    <pre>{{ report.scan_data }}</pre>
                </div>
                </div>
    </div>
  </div>
</div>
{% endblock %}

api/templates/user/reports.html
{% extends "user/profile_base.html" %} {% block title %}Reports{% endblock %}
{% block profile_content %}
<div class="col-12">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="/">Home</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Reports</li>
    </ol>
  </nav>
  <div class="table-responsive">
    <table class="table table-striped table-hover" id="reports_table">
      <thead>
        <tr>
          <th scope="col">Report ID</th>
          <th scope="col">Report Name</th>
          <th scope="col">Report Request Date</th>
          <th scope="col">Report Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody> {% if reports|length == 0 %} <tr>
          <td colspan="4" style="text-align: center;">No reports found. <br>
            <a href="/">Start a scan by clicking here</a>
          </td>
        </tr> {% else %} {% for report in reports %} <tr>
          <td>{{ report.id }}</td>
          <td>{{ report.name }}</td>
          <td>{{ report.date }}</td>
          <td>{{ report.status }}</td>
          <td>
            <button type="button" class="btn btn-primary" onclick="window.location.href='/reports/{{ report.id }}'">View</button> {% if report.status == "READY" %} <button type="button" class="btn btn-success" onclick="window.location.href='/reports/{{ report.id }}/download'">Download</button> {% else %} <button type="button" class="btn btn-outline-primary check_button" id="{{report.id}}" data-task_id="{{report.task_id}}">Check status</button> {% endif %} <form action="/reports/{{ report.id }}/delete" method="POST" style="display: inline;">
              <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this report?')">Delete</button>
            </form>
          </td>
        </tr> {% endfor %} {% endif %} </tbody>
    </table>
  </div>
</div> {% endblock %} {% block scripts %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
	<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
<script>
  $(document).ready(function() {
    $('.check_button').click(function() {
      var task_id = $(this).data('task_id');
      $.ajax({
        url: '/reports/check_status',
        type: 'POST',
        data: {
          task_id: task_id
        },
        success: function(data) {
          if (data['state'] == 'SUCCESS') {
            window.location.reload();
          }
          alert(data['status']);
        }
      });
    });
  });
  $(document).ready(function () {

    $('#reports_table').DataTable({
        "order": [[ 0, "desc" ]]
        });

});
</script> {% endblock %}